dist: xenial

sudo: required

language: python

python:
  - "3.7"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

install:
  - pwd
  - pip install cloudmesh-installer
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
  - ls
  - pwd
  - python --version
  - mkdir -p ~/.cloudmesh
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-cloud/master/cloudmesh/etc/cloudmesh4.yaml


script:
  - pytest -v --capture=no tests/test_cloud_installer.py
  - pytest -v --capture=no tests/test_ping.py
  - pytest -v --capture=no tests/test_check.py
